Added hi-fi tab bar
Klip-Generate/Klip-App pull request #16
Opened 2021-03-17 02:53 UTC by denk0403

<img src="https://user-images.githubusercontent.com/3473945/111407572-52fff300-86aa-11eb-8ae9-7c2fa380c1ad.png" width="500"/>

2021-03-18 21:49 UTC, katetuohy requested changes
The code looks pretty good to me! However, I tried to get it running on my local by cloning it but kept running into this error: 
`Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider`

Not sure what's causing that but is anyone else getting the same? From what I gathered while googling, it looks to be an import error...

2021-03-18 21:57 UTC, denk0403 commented on App.tsx
> +const requireSignIn = false;
Whoops, good catch, that shouldn't be there

2021-03-18 22:03 UTC, denk0403 commented
> The code looks pretty good to me! However, I tried to get it running on my local by cloning it but kept running into this error:
> `Invariant Violation: Tried to register two views with the same name RNCSafeAreaProvider`
> 
> Not sure what's causing that but is anyone else getting the same? From what I gathered while googling, it looks to be an import error...

Did you run `npm i` or `npm ci` before running it? I added a package so maybe that could be related? Also, did it give a line number or stack trace, I'm not getting this error?

2021-04-07 00:00 UTC, mattognibene reviewed
minor comments, my expo is kinda broken right now so i cant run in so I will come back to review more once its fixed

2021-04-07 01:55 UTC, denk0403 commented on App.tsx
> -    const createPublishHandler = (
😁

2021-04-07 01:58 UTC, denk0403 commented on App.tsx
> +                                        tabBarIcon: ({ focused }) => (
React Navigation's Tab component calls this function every time it rerenders and passes that value in (within an object).

2021-04-07 02:02 UTC, denk0403 commented on App.tsx
> +        <SafeAreaView style={{ flex: 1 }}>
`SafeAreaView` is a wrapper component that ensures children views are properly padded so that they are not in the way of parts of the screen such as rounded corners or the camera notch. https://reactnative.dev/docs/safeareaview

2021-04-07 02:07 UTC, denk0403 commented on src/screens/AddContactScreen.tsx
> +            waitFor(saveUserContact).then(() => {
Some lines read so nicely with it like in the AuthScreen component:
```typescript
waitFor(signUpUser({ email, password, name })).then(logIn);
```

2021-04-11 21:52 UTC, mattognibene approved these changes
LGTM, just get an okay from Nadya/Julia on design and we're go to go.

One thing I'd suggest is to try to split up refactoring into a separate PR. That will help make reviewing a little easier and PRs smaller as we can just focus on task at hand. Also, it looks like your code formatter worked extra hard in this PR 😂. What code formatter are you running? If we make it a standard practice to run the code formatting before every merge, we would likely have less bulky PRs as well (ideally, that would come in our CI/CD pipeline but alas we are but mere Generate BSEs)

2021-04-11 21:52 UTC, mattognibene commented on App.tsx
> +            <SessionManagerContext.Provider value={sessionManager}>
is this sessionManager actually being used for anything?

2021-04-11 21:52 UTC, mattognibene commented on src/components/EmergencyCountDown.tsx
> +export default function EmergencyCountDown({
At a quick glance, these changes in this file look fine. Not sure if most of this was just autoformatter, but just a personal preference I'd prefer this to have been in a different PR since it is somewhat unrelated to the hi-fi bar.

2021-04-11 21:52 UTC, mattognibene commented on src/containers/CommunityContainer.tsx
> +export default function CommunityContainer() {
nice, I like how we pulled this into its own container rather than living in the higher level app

2021-04-11 21:52 UTC, mattognibene commented on src/containers/CommunityContainer.tsx
> +    const { session } = useContext(SessionManagerContext)!;
less of a review comment more of a React question, could you wrap your views around in a `SessionManagerContext.Provider` here instead of using the hook? Just wondering since that's how its done in App.tsx, but I might be missing something. This looks fine just curious lol

2021-04-11 21:52 UTC, mattognibene commented on src/screens/AuthScreen/AuthScreen.tsx
> +            <ScrollView>
GitHub is making seeing these changes kinda hard: is the main change here just adding the scroll view?

2021-04-11 23:34 UTC, denk0403 commented on App.tsx
> +            <SessionManagerContext.Provider value={sessionManager}>
It holds our session object which includes information about the current user, making it really easy to retrieve info like the userId from different screens when making API requests.

2021-04-11 23:39 UTC, denk0403 commented on src/screens/AuthScreen/AuthScreen.tsx
> +            <ScrollView>
Lol I think so, it was added just to make the screen work a bit better on smaller devices. Not related to BLE tho, didn't mean to include it here.

2021-04-11 23:42 UTC, denk0403 commented on src/components/EmergencyCountDown.tsx
> +export default function EmergencyCountDown({
I think this was mostly related to merging conflicts and solving a small bug I discovered while testing my merge.

2021-04-11 23:46 UTC, denk0403 commented on src/containers/CommunityContainer.tsx
> +export default function CommunityContainer() {
Yea this is one of the refactoring changes I want to make, more containers. I'm thinking of doing something similar with Sessions when working on the login/signup ticket to make the App.tsx even smaller.

2021-04-18 22:15 UTC, merged