WIP: Countdown Hi-Fis
Klip-Generate/Klip-App pull request #19
Opened 2021-03-24 04:34 UTC by katetuohy

Implement Emergency Countdown to Alert Hi-Fis

I refactored the Emergency Countdown to Alert Screen from being its own screen into being an `overlay` component that can be triggered from any screen when an event occurs. 

Additionally, I mocked up a Run Mode screen to be able to test the triggering of the countdown using the code Dennis had put together on the `ble` branch. 

To still be done:
- Make pretty with the correct colors, fonts, shapes
- Add the `overlay` component to every single screen (not sure this is the best from a design perspective but I don't see any alternatives so please let me know if you think of alternatives)

2021-04-03 18:23 UTC, mattognibene reviewed
Looks good! Left some comments

2021-04-03 18:23 UTC, mattognibene commented on src/components/EmergencyCountDown.tsx
> +                            toggleOverlay();
so is `toggleOverlay()` what is cancelling the emergency?

2021-04-03 18:23 UTC, mattognibene commented on src/components/EmergencyCountDown.tsx
> +export default function EmergencyCountDown({ currentScreen, recipient, navigation, toggleOverlay }: EmergencyCountDownProps) {
General suggestion for this class; It looks like there is a lot of condition checking on `hasSentContactAlert`, `isSendingAlert`, etc for what view to show. To make it a little easier to read, could we pull views out into helper functions? for example

```
!hasSentContactAlert && !hasSentAuthoritiesAlert) ? showSendingView() : showAlertSentView() 
```

2021-04-03 18:23 UTC, mattognibene commented on src/screens/RunModeScreen.tsx
> +    const [visible, setVisible] = useState(false);
`visible` is a little ambiguous as a name

2021-04-05 01:02 UTC, katetuohy commented on src/components/EmergencyCountDown.tsx
> +                            toggleOverlay();
No. Correct me if I'm wrong but I didn't think that we had an endpoint for that. toggleOverlay() just closes the emergency flow

2021-04-06 06:38 UTC, denk0403 requested changes

2021-04-06 06:38 UTC, denk0403 commented on package.json
> +    "react-native-safe-area-context": "3.1.9",
Where does this package get used? If it isn't being used, we should uninstall it and remove it from our dependencies.

2021-04-06 06:38 UTC, denk0403 commented on src/components/EmergencyCountDown.tsx
> +                {hasSentAuthoritiesAlert ?
There is a lot of overlap between the views that show whether emergency contacts or the authorities were notified.  Try to abstract them into a new or a couple of new components. One I'm thinking we definitely should add here is a Modal component. This will also help make this file more readable.

2021-04-06 06:38 UTC, denk0403 commented on src/components/EmergencyCountDown.tsx
> +    const [hasSentAuthoritiesAlert, setHasSentAuthoritiesAlert] = useState(false);
If we introduce a Modal component, would it be possible to combine some of these states into a single state holding onto a status, which determines when to show a Modal and which one.

I'm imagining we can define a type like:
```typescript
type RunStatus = "running" | "loading_contacts" | "loading_authorities" | "sent_contacts" | etc... ;

// inside component
const [status, setStatus] = useState("running");
```
And then we have a pure component which renders different modals based on passed in status:
```tsx
function RunStatusModal({status}: Props) {
    switch (status) {
        case "loading_contacts":
            return <Modal content={CountdownContacts} />;
         case "loading_authorities":
            return <Modal content={CountdownAuthorities} />;
         // etc...
         default:
            return undefined;
    }
}
```

2021-04-06 06:38 UTC, denk0403 commented on src/screens/RunModeScreen.tsx
> +    // useEffect(() => {
I think we can remove these comments since they were just part of the mock Bluetooth device. If we want to trigger emergencies within the app, we can probably add that without the Bluetooth interface.

2021-04-06 21:26 UTC, katetuohy commented on package.json
> +    "react-native-safe-area-context": "3.1.9",
It's an expo dependency and the project will break on expo without it

2021-04-07 02:44 UTC, katetuohy commented on src/components/EmergencyCountDown.tsx
> +    const [hasSentAuthoritiesAlert, setHasSentAuthoritiesAlert] = useState(false);
While I like the idea, I want to focus on the next hi-fis that need to be completed and think that the abstraction that I've done so far is enough. I know this would be better code practice though. I think that if we wanted to refactor it to be like that, it could be a separate ticket

2021-04-08 01:13 UTC, mattognibene commented on src/components/EmergencyCountDown.tsx
> +    const [hasSentAuthoritiesAlert, setHasSentAuthoritiesAlert] = useState(false);
I agree, I think making this an enum is the cleanest solution. Separate state like this grows 2^n, so its good to just make discrete states that the screen can be in.
However, I don't that's a blocking issue for this screen, so I agree we can refactor it later

2021-04-08 01:14 UTC, mattognibene approved these changes
LGTM

2021-04-08 01:14 UTC, mattognibene commented on src/components/EmergencyCountDown.tsx
> +            {(!hasSentContactAlert && !hasSentAuthoritiesAlert) ? {countdown} :
so clean

2021-04-08 01:58 UTC, merged